import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/shared/providers/reactQuery";
import { AuthInitProvider } from "@/shared/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AuthInitProvider>
            {children}
            <Toaster position="top-right" />
          </AuthInitProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
